name: 🚀 Deploy to server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: SSH & Deploy
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            docker pull great2005/api-image:latest
            docker stop api || true
            docker rm api || true
            docker run -d -p 3000:3000 --name api great2005/api-image:latest

            docker pull great2005/webapp-image:latest
            docker stop webapp || true
            docker rm webapp || true
            docker run -d -p 80:5000 --name webapp great2005/webapp-image:latest
